### ISSUE TITLE
storybookの導入

### ISSUE THREAD

**Issue by yukomakino** [kei-nishikawa48/youtube-music-lyrics#5]
## 概要

- storybookを導入する

**Comment by kei-nishikawa48** [comment]
素晴らしいです！
一点思ったのが、こちらwebpackでおこなっているみたいなのですが、sveltekitはviteというバンドらが使われているので
storybookもviteで統一したいです！

おそらくstorybookが立ち上がるスピードとかも早くなるはずなのでチャレンジしてみてほしいです！

**Comment by yukomakino** [comment]
承知いたしました。
viteについて調べてみます！
コメントありがとうございます。
